name: CI-unit-tests

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job1:
    pytest:
      name: testing
      runs-on: ubuntu-20.04

      steps:
        - name: Checkout acse_la
          uses: actions/checkout@v2

        - name: Set test directory
          run: |
            echo "::set-env name=TESTS::tests/"

        - name: Install dependencies
          run: |
            sudo apt-get install python3-setuptools -y
            pip3 install --upgrade pip
            pip3 install -e .
            pip3 install -r requirements.txt

        - name: Set a run prefix
          run: |
            echo "::set-env name=RUN::python3 -m"

        - name: Test with pytest
          run: |
            $RUN pytest $TESTS


  job2:
    pytest:
      name: testing
      runs-on: macos-11.0

      steps:
        - name: Checkout acse_la
          uses: actions/checkout@v2

        - name: Set test directory
          run: |
            echo "::set-env name=TESTS::tests/"

        - name: Install dependencies
          run: |
            sudo apt-get install python3-setuptools -y
            pip3 install --upgrade pip
            pip3 install -e .
            pip3 install -r requirements.txt

        - name: Set a run prefix
          run: |
            echo "::set-env name=RUN::python3 -m"

        - name: Test with pytest
          run: |
            $RUN pytest $TESTS




  job3:
    pytest:
      name: testing
      runs-on: windows-2019

      steps:
        - name: Checkout acse_la
          uses: actions/checkout@v2

        - name: Set up Python 3.7
            uses: actions/setup-python@v1
            with:
              python-version: 3.7

        - name: Set test directory
          run: |
            echo "::set-env name=TESTS::tests/"

        - name: Install dependencies
          run: |
            pip install --upgrade pip
            pip install -e .
            pip install -r requirements.txt

        - name: Set a run prefix
          run: |
            echo "::set-env name=RUN::python -m"

        - name: Test with pytest
          run: |
            %RUN% pytest %TESTS%



